### ISSUE TITLE
Feature Request: defclass

### ISSUE THREAD

**Issue by jgarte** [ciel-lang/more-docstrings#1]
https://novaspec.org/cl/f_defclass

WDYT

**Comment by vindarel** [comment]
Hi, yes sure it's needed. Thanks for the reminder, I've been using this package daily but I have slowly forgotten it.

**Comment by jgarte** [comment]
Great, I'll create more issues as I think of them. If I feel that I can contribute to one of them then I'll open a PR as well.

**Comment by vindarel** [comment]
> Great, I'll create more issues as I think of them. If I feel that I can contribute to one of them then I'll open a PR as well.

mmh actually it is not necessary to create issues for missing items, because thousands of entries are missing! You can just open a PR.

**Comment by jgarte** [comment]
The issue is (no pun) that I might not be the right person to open the PR at the moment but I'd like to create the issue in order to motivate others that might then open the PR if they have the skills, expertise, time. 

Would that be too noisy here?

**Comment by vindarel** [comment]
yes, in the case of this library it would be too noisy, because the issue wouldn't be a software issue but simply about adding documentation for a symbol. And it's also a simple addition, it's easy to know what needs to be done.
